AWSTemplateFormatVersion: "2010-09-09"
Description: creating codebuild and code pipeline service

Resources:
 EventBridgeRule:
   Type: AWS::Events::Rule
   Properties:
     Name: Test 
     Description: "emr-state-change-EventRule"
     EventPattern: 
      source: 
         - 'aws.emr'
      detail-type: 
          - 'EMR Cluster State Change'
      detail: 
         state:
           - 'STARTING'
     State: "ENABLED"
     Targets: 
       - Arn: arn:aws:lambda:us-east-1:107406514706:function:filestransfer
         Id: "filestransfer"
